# Generated by Django 4.2.4 on 2023-08-07 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_user_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('flight_no', models.CharField(max_length=6)),
                ('depart_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('is_nonstop', models.BooleanField(default=False)),
                ('economy_fare', models.FloatField()),
                ('buisness_fare', models.FloatField()),
                ('first_class_fare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Others')], max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='+91-XXXXXXXXXX', max_length=14),
        ),
        migrations.CreateModel(
            name='Layover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layovers', to='flight.flight')),
                ('next_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_weekday',
            field=models.ManyToManyField(to='flight.week'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_weekday',
            field=models.ManyToManyField(related_name='flights_of_the_day', to='flight.week'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flight.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flight.airport'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=6)),
                ('payment_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_status', models.CharField(choices=[('NO_INITIALISED', 'Not Initialised'), ('CREATED', 'Created')], default='NOT_INITIALISED', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booked_at', models.DateTimeField(auto_now=True)),
                ('flight_dep_date', models.DateField()),
                ('flight_arriv_date', models.DateField()),
                ('mobile_no', models.CharField(max_length=12)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUISNESS', 'Buisness'), ('FIRST_CLASS', 'First_class')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMAED', 'Confirmed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=15)),
                ('flight_fare', models.FloatField()),
                ('coupon_used', models.CharField(blank=True, max_length=10)),
                ('coupon_discount', models.FloatField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_tickets', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flight.flight')),
                ('passengers', models.ManyToManyField(related_name='ticket_bookings', to='flight.passenger')),
            ],
        ),
    ]
