# Generated by Django 4.2.4 on 2023-08-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airport_flight_passenger_week_user_mobile_no_layover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(default=220),
        ),
    ]
