# Generated by Django 4.2.4 on 2023-08-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_seats_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='week_number',
            new_name='number',
        ),
    ]
