# Generated by Django 4.2.4 on 2023-08-09 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_rename_week_number_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
