# Generated by Django 4.2.4 on 2023-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_alter_flight_is_nonstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_code',
            field=models.CharField(default='CO', max_length=3),
        ),
    ]
