# Generated by Django 4.2.4 on 2023-08-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_flight_flight_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='layover',
            name='airport_change',
            field=models.BooleanField(default=False),
        ),
    ]
