# Generated by Django 4.2.4 on 2023-08-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_layover_airport_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layover',
            old_name='next_flight',
            new_name='connecting_flight',
        ),
    ]
