# Generated by Django 4.2.4 on 2023-08-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_rename_next_flight_layover_connecting_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coupon_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
