# Generated by Django 4.2.4 on 2023-08-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_remove_booking_mobile_no_booking_coupon_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight_fare',
            new_name='total_fare',
        ),
    ]
