# Generated by Django 4.2.4 on 2023-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_rename_flight_fare_booking_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
