# Generated by Django 4.2.4 on 2023-08-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_passenger_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
    ]
