# Generated by Django 4.2.4 on 2023-08-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0016_rename_status_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.FloatField(default=0.0),
        ),
    ]
