# Generated by Django 4.2.4 on 2023-08-23 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_alter_booking_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
