# Generated by Django 4.2.4 on 2023-08-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_passenger_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(blank=True, choices=[('WINDOW', 'Window'), ('AISLE', 'Aisle'), ('MIDDLE', 'Middle')], max_length=10)),
                ('seat_no', models.CharField(blank=True, max_length=3)),
                ('departure_date', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight.flight')),
                ('passenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight.passenger')),
            ],
            options={
                'unique_together': {('flight', 'departure_date', 'seat_no')},
            },
        ),
    ]
