# Generated by Django 4.2.4 on 2023-08-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0019_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='seat_type',
        ),
    ]
