# Generated by Django 4.2.4 on 2023-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0020_remove_seats_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='seat_type',
            field=models.CharField(blank=True, choices=[('WINDOW', 'Window'), ('AISLE', 'Aisle'), ('MIDDLE', 'Middle')], max_length=10),
        ),
    ]
