# Generated by Django 4.2.4 on 2023-08-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0021_seats_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight.passenger'),
        ),
    ]
