# Generated by Django 4.2.4 on 2023-08-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0022_alter_seats_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
