# Generated by Django 4.2.4 on 2023-08-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0024_passenger_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
