# Generated by Django 4.2.4 on 2023-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0026_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_reciept_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
