# Generated by Django 4.2.4 on 2023-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0027_booking_refund_reciept_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('SUCCEDED', 'Succeded'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing'), ('NOT_ATTEMPTED', 'Not Attempted')], default='NOT_ATTEMPTED', max_length=15),
        ),
    ]
