# Generated by Django 4.2.4 on 2023-08-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0028_alter_booking_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='refund_reciept_url',
            new_name='refund_receipt_url',
        ),
    ]
