# Generated by Django 4.2.4 on 2023-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0029_rename_refund_reciept_url_booking_refund_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='extra_baggage_booking_mode',
            field=models.CharField(blank=True, choices=[('PRE-BOOKING', 'Pre_booking'), ('AT_AIRPORT', 'At_Airport')], null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='hand_baggage',
            field=models.FloatField(default=0.0),
        ),
    ]
