# Generated by Django 4.2.4 on 2023-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0030_passenger_extra_baggage_booking_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_baggage',
            field=models.FloatField(default=0.0),
        ),
    ]
