# Generated by Django 4.2.4 on 2023-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0031_booking_check_in_baggage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_baggage',
        ),
        migrations.AddField(
            model_name='passenger',
            name='check_in_baggage',
            field=models.FloatField(default=0.0),
        ),
    ]
