# Generated by Django 4.2.4 on 2023-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0032_remove_booking_check_in_baggage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='extra_baggage_booking_mode',
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_baggage_booking_mode',
            field=models.CharField(blank=True, choices=[('PRE-BOOKING', 'Pre_booking'), ('AT_AIRPORT', 'At_Airport')], null=True),
        ),
    ]
