# Generated by Django 4.2.4 on 2023-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0033_remove_passenger_extra_baggage_booking_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_baggage_price',
            field=models.FloatField(default=0.0),
        ),
    ]
