# Generated by Django 4.2.4 on 2023-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0037_booking_is_return_type_booking_return_flight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_return_type',
            new_name='round_trip',
        ),
    ]
