# Generated by Django 4.2.4 on 2023-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0038_rename_is_return_type_booking_round_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='round_trip',
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('ROUND_TRIP', 'Round Trip'), ('ONE WAY', 'One Way')], default='ONE WAY', max_length=15),
        ),
    ]
