# Generated by Django 4.2.4 on 2023-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0040_alter_booking_trip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='return_flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_flight_arriv_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_flight_dep_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='other_booking_ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='separate_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
