# Generated by Django 4.2.4 on 2023-10-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0041_remove_booking_return_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='separate_ticket',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
    ]
