FROM python:3.10-alpine

WORKDIR /app
COPY requirements.txt .

RUN \
    apk add --no-cache postgresql-libs  &&  \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip3 install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps 

RUN pip3 install -r requirements.txt
#ENV REDIS_URL=$REDIS_URL
COPY . .

# Define your Flower command
CMD ["celery", "-A", "flight", "flower"]